/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment.assignment.Buildingmanager;

/**
 *
 * @author user
 */
public class Usermanagementmenu extends javax.swing.JFrame {

    /**
     * Creates new form usermanagementmenu
     */
    public Usermanagementmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountexecutiveuserPANEL = new javax.swing.JPanel();
        accountexecutiveaddBTN = new javax.swing.JButton();
        accountexecutivemodifyBTN = new javax.swing.JButton();
        buildingexecutiveuserPANEL = new javax.swing.JPanel();
        buildingexecutiveaddBTN = new javax.swing.JButton();
        buildingexecutivemodifyBTN = new javax.swing.JButton();
        usermanagementLABEL = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accountexecutiveuserPANEL.setBorder(javax.swing.BorderFactory.createTitledBorder("Manage Account Executive"));

        accountexecutiveaddBTN.setText("Add");
        accountexecutiveaddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountexecutiveaddBTNActionPerformed(evt);
            }
        });

        accountexecutivemodifyBTN.setText("Modify");

        javax.swing.GroupLayout accountexecutiveuserPANELLayout = new javax.swing.GroupLayout(accountexecutiveuserPANEL);
        accountexecutiveuserPANEL.setLayout(accountexecutiveuserPANELLayout);
        accountexecutiveuserPANELLayout.setHorizontalGroup(
            accountexecutiveuserPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountexecutiveuserPANELLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(accountexecutiveaddBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(accountexecutivemodifyBTN)
                .addGap(44, 44, 44))
        );
        accountexecutiveuserPANELLayout.setVerticalGroup(
            accountexecutiveuserPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountexecutiveuserPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountexecutiveuserPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountexecutiveaddBTN)
                    .addComponent(accountexecutivemodifyBTN))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        buildingexecutiveuserPANEL.setBorder(javax.swing.BorderFactory.createTitledBorder("Manage Building Executive"));

        buildingexecutiveaddBTN.setText("Add");

        buildingexecutivemodifyBTN.setText("Modify");

        javax.swing.GroupLayout buildingexecutiveuserPANELLayout = new javax.swing.GroupLayout(buildingexecutiveuserPANEL);
        buildingexecutiveuserPANEL.setLayout(buildingexecutiveuserPANELLayout);
        buildingexecutiveuserPANELLayout.setHorizontalGroup(
            buildingexecutiveuserPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buildingexecutiveuserPANELLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(buildingexecutiveaddBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buildingexecutivemodifyBTN)
                .addGap(41, 41, 41))
        );
        buildingexecutiveuserPANELLayout.setVerticalGroup(
            buildingexecutiveuserPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buildingexecutiveuserPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buildingexecutiveuserPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buildingexecutiveaddBTN)
                    .addComponent(buildingexecutivemodifyBTN))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        usermanagementLABEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usermanagementLABEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usermanagementLABEL.setText("User Management");

        backBTN.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buildingexecutiveuserPANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountexecutiveuserPANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usermanagementLABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBTN)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBTN)
                    .addComponent(usermanagementLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountexecutiveuserPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(buildingexecutiveuserPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountexecutiveaddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountexecutiveaddBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountexecutiveaddBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usermanagementmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usermanagementmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usermanagementmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usermanagementmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usermanagementmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountexecutiveaddBTN;
    private javax.swing.JButton accountexecutivemodifyBTN;
    private javax.swing.JPanel accountexecutiveuserPANEL;
    private javax.swing.JButton backBTN;
    private javax.swing.JButton buildingexecutiveaddBTN;
    private javax.swing.JButton buildingexecutivemodifyBTN;
    private javax.swing.JPanel buildingexecutiveuserPANEL;
    private javax.swing.JLabel usermanagementLABEL;
    // End of variables declaration//GEN-END:variables
}
