/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assignment.assignment.Adminexecutive;

/**
 *
 * @author user
 */
public class Adminexecutivemenu extends javax.swing.JPanel {

    /**
     * Creates new form adminexecutivemenu
     */
    public Adminexecutivemenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminexecutiveLABEL = new javax.swing.JLabel();
        unitmanagementBTN = new javax.swing.JButton();
        tenantmanagementBTN = new javax.swing.JButton();
        complaintmanagementBTN = new javax.swing.JButton();
        employeemanagementBTN = new javax.swing.JButton();
        facilitymanagementBTN = new javax.swing.JButton();
        facilitybookingmanagementBTN = new javax.swing.JButton();
        logoutBTN = new javax.swing.JButton();

        adminexecutiveLABEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminexecutiveLABEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminexecutiveLABEL.setText("Admin Executive");

        unitmanagementBTN.setText("Unit Management");

        tenantmanagementBTN.setText("Resident/Tenant Management");
        tenantmanagementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantmanagementBTNActionPerformed(evt);
            }
        });

        complaintmanagementBTN.setText("Complaint Management");

        employeemanagementBTN.setText("Employee Management");

        facilitymanagementBTN.setText("Facility management ");
        facilitymanagementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facilitymanagementBTNActionPerformed(evt);
            }
        });

        facilitybookingmanagementBTN.setText("Facility Booking management ");

        logoutBTN.setText("LogOut");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adminexecutiveLABEL, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(logoutBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenantmanagementBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unitmanagementBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(complaintmanagementBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeemanagementBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facilitymanagementBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facilitybookingmanagementBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutBTN)
                    .addComponent(adminexecutiveLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitmanagementBTN)
                .addGap(18, 18, 18)
                .addComponent(tenantmanagementBTN)
                .addGap(18, 18, 18)
                .addComponent(complaintmanagementBTN)
                .addGap(18, 18, 18)
                .addComponent(employeemanagementBTN)
                .addGap(18, 18, 18)
                .addComponent(facilitymanagementBTN)
                .addGap(18, 18, 18)
                .addComponent(facilitybookingmanagementBTN)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tenantmanagementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantmanagementBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenantmanagementBTNActionPerformed

    private void facilitymanagementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facilitymanagementBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facilitymanagementBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminexecutiveLABEL;
    private javax.swing.JButton complaintmanagementBTN;
    private javax.swing.JButton employeemanagementBTN;
    private javax.swing.JButton facilitybookingmanagementBTN;
    private javax.swing.JButton facilitymanagementBTN;
    private javax.swing.JButton logoutBTN;
    private javax.swing.JButton tenantmanagementBTN;
    private javax.swing.JButton unitmanagementBTN;
    // End of variables declaration//GEN-END:variables
}
