/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment.assignment.AdminExecutives;

import assignment.assignment.LoginPage;
import assignment.assignment.User;

/**
 *
 * @author user
 */
public class AdminExecutiveMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminExecutiveMenu
     */
    public AdminExecutiveMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public AdminExecutiveMenu(User user) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminexecutiveLABEL = new javax.swing.JLabel();
        logoutBTN = new javax.swing.JButton();
        facilitybookingmanagementBTN = new javax.swing.JButton();
        facilitymanagementBTN = new javax.swing.JButton();
        employeemanagementBTN = new javax.swing.JButton();
        complaintmanagementBTN = new javax.swing.JButton();
        tenantmanagementBTN = new javax.swing.JButton();
        unitmanagementBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminexecutiveLABEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminexecutiveLABEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminexecutiveLABEL.setText("Admin Executive");

        logoutBTN.setText("LogOut");
        logoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTNActionPerformed(evt);
            }
        });

        facilitybookingmanagementBTN.setText("Facility Booking management ");
        facilitybookingmanagementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facilitybookingmanagementBTNActionPerformed(evt);
            }
        });

        facilitymanagementBTN.setText("Facility management ");
        facilitymanagementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facilitymanagementBTNActionPerformed(evt);
            }
        });

        employeemanagementBTN.setText("Employee Management");
        employeemanagementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeemanagementBTNActionPerformed(evt);
            }
        });

        complaintmanagementBTN.setText("Complaint Management");
        complaintmanagementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complaintmanagementBTNActionPerformed(evt);
            }
        });

        tenantmanagementBTN.setText("Resident/Tenant Management");
        tenantmanagementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantmanagementBTNActionPerformed(evt);
            }
        });

        unitmanagementBTN.setText("Unit Management");
        unitmanagementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitmanagementBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adminexecutiveLABEL, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(logoutBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenantmanagementBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unitmanagementBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(complaintmanagementBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeemanagementBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facilitymanagementBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facilitybookingmanagementBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutBTN)
                    .addComponent(adminexecutiveLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitmanagementBTN)
                .addGap(18, 18, 18)
                .addComponent(tenantmanagementBTN)
                .addGap(18, 18, 18)
                .addComponent(complaintmanagementBTN)
                .addGap(18, 18, 18)
                .addComponent(employeemanagementBTN)
                .addGap(18, 18, 18)
                .addComponent(facilitymanagementBTN)
                .addGap(18, 18, 18)
                .addComponent(facilitybookingmanagementBTN)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTNActionPerformed
        // TODO add your handling code here:
        LoginPage LoginPage = new LoginPage();
        this.dispose();
        LoginPage.setVisible(true);
    }//GEN-LAST:event_logoutBTNActionPerformed

    private void facilitymanagementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facilitymanagementBTNActionPerformed
        // TODO add your handling code here:
        FacilityManagementMenu FacilityManagementMenu = new FacilityManagementMenu();
        this.dispose();
        FacilityManagementMenu.setVisible(true);
    }//GEN-LAST:event_facilitymanagementBTNActionPerformed

    private void tenantmanagementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantmanagementBTNActionPerformed
        // TODO add your handling code here:
        TenantManagementMenu TenantManagementMenu = new TenantManagementMenu();
        this.dispose();
        TenantManagementMenu.setVisible(true);
    }//GEN-LAST:event_tenantmanagementBTNActionPerformed

    private void unitmanagementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitmanagementBTNActionPerformed
        // TODO add your handling code here:
        UnitManagementMenu UnitManagementMenu = new UnitManagementMenu();
        this.dispose();
        UnitManagementMenu.setVisible(true);
    }//GEN-LAST:event_unitmanagementBTNActionPerformed

    private void complaintmanagementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complaintmanagementBTNActionPerformed
        // TODO add your handling code here:
        ComplaintManagementMenu ComplaintManagementMenu = new ComplaintManagementMenu();
        this.dispose();
        ComplaintManagementMenu.setVisible(true);
    }//GEN-LAST:event_complaintmanagementBTNActionPerformed

    private void employeemanagementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeemanagementBTNActionPerformed
        // TODO add your handling code here:
        EmployeeManagementMenu EmployeeManagementMenu = new EmployeeManagementMenu();
        this.dispose();
        EmployeeManagementMenu.setVisible(true);
    }//GEN-LAST:event_employeemanagementBTNActionPerformed

    private void facilitybookingmanagementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facilitybookingmanagementBTNActionPerformed
        // TODO add your handling code here:
        FacilityBookingManagementMenu FacilityBookingManagementMenu = new FacilityBookingManagementMenu();
        this.dispose();
        FacilityBookingManagementMenu.setVisible(true);
    }//GEN-LAST:event_facilitybookingmanagementBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminExecutiveMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminExecutiveMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminExecutiveMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminExecutiveMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminExecutiveMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminexecutiveLABEL;
    private javax.swing.JButton complaintmanagementBTN;
    private javax.swing.JButton employeemanagementBTN;
    private javax.swing.JButton facilitybookingmanagementBTN;
    private javax.swing.JButton facilitymanagementBTN;
    private javax.swing.JButton logoutBTN;
    private javax.swing.JButton tenantmanagementBTN;
    private javax.swing.JButton unitmanagementBTN;
    // End of variables declaration//GEN-END:variables
}
