/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment.assignment.AdminExecutives;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class EmployeeModify extends javax.swing.JFrame {

    /**
     * Creates new form Employeemodify
     */
    public EmployeeModify() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBTN = new javax.swing.JButton();
        employeemodifyLABEL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeemodifyTABLE = new javax.swing.JTable();
        viewemployeeBTN = new javax.swing.JButton();
        modifyBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        employeemodifyLABEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeemodifyLABEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeemodifyLABEL.setText("Employee Modify");

        employeemodifyTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "EmployeeID", "UserID", "Name", "Email", "Password", "Task"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(employeemodifyTABLE);

        viewemployeeBTN.setText("View Employee");
        viewemployeeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewemployeeBTNActionPerformed(evt);
            }
        });

        modifyBTN.setText("Modify");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modifyBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewemployeeBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(employeemodifyLABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(backBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeemodifyLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewemployeeBTN)
                    .addComponent(modifyBTN))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        EmployeeManagementMenu EmployeeManagementMenu = new EmployeeManagementMenu();
        this.dispose();
        EmployeeManagementMenu.setVisible(true);
    }//GEN-LAST:event_backBTNActionPerformed

    private void viewemployeeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewemployeeBTNActionPerformed
        // TODO add your handling code here:
        try {
            File userInfoFile = new File("src/main/java/assignment/assignment/TxtFile/UserInfo.txt");
            File employeeInfoFile = new File("src/main/java/assignment/assignment/TxtFile/EmployeeInfo.txt");
            FileReader userInfoReader = new FileReader(userInfoFile);
            FileReader employeeInfoReader = new FileReader(employeeInfoFile);
            BufferedReader userInfoBR = new BufferedReader(userInfoReader);
            BufferedReader employeeInfoBR = new BufferedReader(employeeInfoReader);
            String userInfoLine, employeeInfoLine;
            DefaultTableModel model = (DefaultTableModel) employeemodifyTABLE.getModel();
            model.setRowCount(0);
            userInfoBR.readLine(); // Skip header row in UserInfo.txt
            employeeInfoBR.readLine(); // Skip header row in TenantInfo.txt
            while ((userInfoLine = userInfoBR.readLine()) != null) {
                String[] userInfoData = userInfoLine.split(";");
                while ((employeeInfoLine = employeeInfoBR.readLine()) != null) {
                    String[] employeeInfoData = employeeInfoLine.split(";");
                    if (employeeInfoData[2].equals(userInfoData[0])) { // Match UserID
                        Object[] row = { employeeInfoData[0], userInfoData[0], userInfoData[3], userInfoData[4], userInfoData[1], employeeInfoData[1] };
                        model.addRow(row);
                        break; // Exit tenantInfo loop when match is found
                    }
                }
                employeeInfoBR.close();
                employeeInfoReader = new FileReader(employeeInfoFile); // Reset tenantInfoReader
                employeeInfoBR = new BufferedReader(employeeInfoReader); // Reset tenantInfoBR
                employeeInfoBR.readLine(); // Skip header row in TenantInfo.txt
            }
            userInfoBR.close();
            userInfoReader.close();
            employeeInfoBR.close();
            employeeInfoReader.close();
        } catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_viewemployeeBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeModify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel employeemodifyLABEL;
    private javax.swing.JTable employeemodifyTABLE;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifyBTN;
    private javax.swing.JButton viewemployeeBTN;
    // End of variables declaration//GEN-END:variables
}
