/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment.assignment.AdminExecutives;

/**
 *
 * @author user
 */
public class TenantManagementMenu extends javax.swing.JFrame {

    /**
     * Creates new form tenantmanagementmenu
     */
    public TenantManagementMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBTN = new javax.swing.JButton();
        tenantmanagementLABEL = new javax.swing.JLabel();
        managetenantPANEL = new javax.swing.JPanel();
        tenantnewBTN = new javax.swing.JButton();
        tenantmodifyBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        tenantmanagementLABEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenantmanagementLABEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tenantmanagementLABEL.setText("Resident/Tenant Management");

        managetenantPANEL.setBorder(javax.swing.BorderFactory.createTitledBorder("Manage Tenant"));

        tenantnewBTN.setText("Add");
        tenantnewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantnewBTNActionPerformed(evt);
            }
        });

        tenantmodifyBTN.setText("Modify");
        tenantmodifyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantmodifyBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout managetenantPANELLayout = new javax.swing.GroupLayout(managetenantPANEL);
        managetenantPANEL.setLayout(managetenantPANELLayout);
        managetenantPANELLayout.setHorizontalGroup(
            managetenantPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managetenantPANELLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(tenantnewBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(tenantmodifyBTN)
                .addGap(15, 15, 15))
        );
        managetenantPANELLayout.setVerticalGroup(
            managetenantPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managetenantPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(managetenantPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenantnewBTN)
                    .addComponent(tenantmodifyBTN))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(managetenantPANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tenantmanagementLABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(backBTN)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tenantmanagementLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(managetenantPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        AdminExecutiveMenu AdminExecutiveMenu = new AdminExecutiveMenu();
        this.dispose();
        AdminExecutiveMenu.setVisible(true);
    }//GEN-LAST:event_backBTNActionPerformed

    private void tenantnewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantnewBTNActionPerformed
        // TODO add your handling code here:
        TenantNew TenantNew = new TenantNew();
        this.dispose();
        TenantNew.setVisible(true);
    }//GEN-LAST:event_tenantnewBTNActionPerformed

    private void tenantmodifyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantmodifyBTNActionPerformed
        // TODO add your handling code here:
        TenantModify TenantModify = new TenantModify();
        this.dispose();
        TenantModify.setVisible(true);
    }//GEN-LAST:event_tenantmodifyBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TenantManagementMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TenantManagementMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TenantManagementMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TenantManagementMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TenantManagementMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JPanel managetenantPANEL;
    private javax.swing.JLabel tenantmanagementLABEL;
    private javax.swing.JButton tenantmodifyBTN;
    private javax.swing.JButton tenantnewBTN;
    // End of variables declaration//GEN-END:variables
}
