package assignment.assignment.SecurityManagementSystem;

import assignment.assignment.User;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author leeyu
 */
public class SecurityGuardMain extends javax.swing.JFrame {
    private User user;

    /**
     * Creates new form SecuritySystem
     */
    public SecurityGuardMain(User user) {
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageVisitorPassBtn = new javax.swing.JButton();
        visitorEntryBtn = new javax.swing.JButton();
        recordIncidentBtn = new javax.swing.JButton();
        checkpointCheckInBtn = new javax.swing.JButton();
        searchVisitorBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        visitorDepartBtn = new javax.swing.JButton();
        CheckInList = new javax.swing.JComboBox<>();
        updateIncidentBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageVisitorPassBtn.setText("View Visitor Pass");
        manageVisitorPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVisitorPassBtnActionPerformed(evt);
            }
        });

        visitorEntryBtn.setText("Visitor Entry Form");
        visitorEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorEntryBtnActionPerformed(evt);
            }
        });

        recordIncidentBtn.setText("Record Incident");
        recordIncidentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordIncidentBtnActionPerformed(evt);
            }
        });

        checkpointCheckInBtn.setText("Checkpoint Check-in");

        searchVisitorBtn.setText("Search Visitor Pass");
        searchVisitorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchVisitorBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Security Guard");

        visitorDepartBtn.setText("Visitor Departure Form");
        visitorDepartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorDepartBtnActionPerformed(evt);
            }
        });

        CheckInList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        updateIncidentBtn.setText("Update Incident");
        updateIncidentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateIncidentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageVisitorPassBtn)
                            .addComponent(visitorEntryBtn)
                            .addComponent(CheckInList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recordIncidentBtn))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateIncidentBtn)
                            .addComponent(visitorDepartBtn)
                            .addComponent(searchVisitorBtn)
                            .addComponent(checkpointCheckInBtn))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchVisitorBtn)
                    .addComponent(manageVisitorPassBtn))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visitorEntryBtn)
                    .addComponent(visitorDepartBtn))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recordIncidentBtn)
                    .addComponent(updateIncidentBtn))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkpointCheckInBtn)
                    .addComponent(CheckInList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageVisitorPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVisitorPassBtnActionPerformed
        // TODO add your handling code here:
        new VisitorPassView(user).setVisible(true);
        dispose();
    }//GEN-LAST:event_manageVisitorPassBtnActionPerformed

    private void searchVisitorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchVisitorBtnActionPerformed
        // TODO add your handling code here:
        new VisitorPassSearch(user).setVisible(true);
        dispose();
    }//GEN-LAST:event_searchVisitorBtnActionPerformed

    private void visitorEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorEntryBtnActionPerformed
        // TODO add your handling code here:
        new VisitorEntryForm(user).setVisible(true);
        dispose();
    }//GEN-LAST:event_visitorEntryBtnActionPerformed

    private void visitorDepartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorDepartBtnActionPerformed
        // TODO add your handling code here:
        new VisitorDepartureForm(user).setVisible(true);
        dispose();
    }//GEN-LAST:event_visitorDepartBtnActionPerformed

    private void updateIncidentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateIncidentBtnActionPerformed
        // TODO add your handling code here:
        new IncidentUpdateForm(user).setVisible(true);
        dispose();
    }//GEN-LAST:event_updateIncidentBtnActionPerformed

    private void recordIncidentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordIncidentBtnActionPerformed
        // TODO add your handling code here:
        new IncidentForm(user).setVisible(true);
        dispose();
    }//GEN-LAST:event_recordIncidentBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecurityGuardMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecurityGuardMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecurityGuardMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecurityGuardMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CheckInList;
    private javax.swing.JButton checkpointCheckInBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageVisitorPassBtn;
    private javax.swing.JButton recordIncidentBtn;
    private javax.swing.JButton searchVisitorBtn;
    private javax.swing.JButton updateIncidentBtn;
    private javax.swing.JButton visitorDepartBtn;
    private javax.swing.JButton visitorEntryBtn;
    // End of variables declaration//GEN-END:variables
}
