/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment.assignment.BuildingManagers;

import assignment.assignment.LoginPage1;
import assignment.assignment.User;

/**
 *
 * @author user
 */
public class BuildingManagerMenu extends javax.swing.JFrame {

    /**
     * Creates new form buildingmanagermenu
     */
    public BuildingManagerMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public BuildingManagerMenu(User user) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usermanagementBTN = new javax.swing.JButton();
        managereportBTN = new javax.swing.JButton();
        operationsandbudgetplanningBTN = new javax.swing.JButton();
        LogoutBTN = new javax.swing.JButton();
        teamstructuremanagementBTN = new javax.swing.JButton();
        buildingmanagerLABEL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usermanagementBTN.setText("User Management");
        usermanagementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usermanagementBTNActionPerformed(evt);
            }
        });

        managereportBTN.setText("Manage Report");
        managereportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managereportBTNActionPerformed(evt);
            }
        });

        operationsandbudgetplanningBTN.setText("Operations and Budget Planning");
        operationsandbudgetplanningBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationsandbudgetplanningBTNActionPerformed(evt);
            }
        });

        LogoutBTN.setText("LogOut");
        LogoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBTNActionPerformed(evt);
            }
        });

        teamstructuremanagementBTN.setText("Team Structure Management");
        teamstructuremanagementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamstructuremanagementBTNActionPerformed(evt);
            }
        });

        buildingmanagerLABEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buildingmanagerLABEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildingmanagerLABEL.setText("Building Manager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(teamstructuremanagementBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(operationsandbudgetplanningBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(managereportBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usermanagementBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buildingmanagerLABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogoutBTN)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buildingmanagerLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutBTN))
                .addGap(18, 18, 18)
                .addComponent(usermanagementBTN)
                .addGap(18, 18, 18)
                .addComponent(managereportBTN)
                .addGap(18, 18, 18)
                .addComponent(operationsandbudgetplanningBTN)
                .addGap(18, 18, 18)
                .addComponent(teamstructuremanagementBTN)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBTNActionPerformed
        // TODO add your handling code here:
        LoginPage1 LoginPage = new LoginPage1();
        this.dispose();
        LoginPage.setVisible(true);
    }//GEN-LAST:event_LogoutBTNActionPerformed

    private void usermanagementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usermanagementBTNActionPerformed
        // TODO add your handling code here:
        UserManagementMenu UserManagementMenu = new UserManagementMenu();
        this.dispose();
        UserManagementMenu.setVisible(true);
    }//GEN-LAST:event_usermanagementBTNActionPerformed

    private void managereportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managereportBTNActionPerformed
        // TODO add your handling code here:
        ManageReportMenu ManageReportMenu = new ManageReportMenu();
        this.dispose();
        ManageReportMenu.setVisible(true);
    }//GEN-LAST:event_managereportBTNActionPerformed

    private void operationsandbudgetplanningBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationsandbudgetplanningBTNActionPerformed
        // TODO add your handling code here:
        OperationsAndBudgetPlanningMenu OperationsAndBudgetPlanningMenu = new OperationsAndBudgetPlanningMenu();
        this.dispose();
        OperationsAndBudgetPlanningMenu.setVisible(true);
    }//GEN-LAST:event_operationsandbudgetplanningBTNActionPerformed

    private void teamstructuremanagementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamstructuremanagementBTNActionPerformed
        // TODO add your handling code here:
        TeamStructureManagementMenu TeamStructureManagementMenu = new TeamStructureManagementMenu();
        this.dispose();
        TeamStructureManagementMenu.setVisible(true);
    }//GEN-LAST:event_teamstructuremanagementBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuildingManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuildingManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuildingManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuildingManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuildingManagerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBTN;
    private javax.swing.JLabel buildingmanagerLABEL;
    private javax.swing.JButton managereportBTN;
    private javax.swing.JButton operationsandbudgetplanningBTN;
    private javax.swing.JButton teamstructuremanagementBTN;
    private javax.swing.JButton usermanagementBTN;
    // End of variables declaration//GEN-END:variables
}
