/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment.assignment.BuildingManagers;

import static assignment.assignment.AdminExecutives.FacilityNew.generateNewFacilityID;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class FundAllocationAdd extends javax.swing.JFrame {

    /**
     * Creates new form Fundallocationadd
     */
    public FundAllocationAdd() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundallocationaddLABEL = new javax.swing.JLabel();
        fundallocationaddPANEL = new javax.swing.JPanel();
        salariesLABEL = new javax.swing.JLabel();
        othersLABEL = new javax.swing.JLabel();
        unitsLABEL = new javax.swing.JLabel();
        facilitiesLABEL = new javax.swing.JLabel();
        salariesTF = new javax.swing.JTextField();
        unitsTF = new javax.swing.JTextField();
        facilitiesTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        descriptionsLABEL = new javax.swing.JLabel();
        othersTF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionsTA = new javax.swing.JTextArea();
        totalTF = new javax.swing.JTextField();
        totalLABEL = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fundallocationaddLABEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fundallocationaddLABEL.setText("Fund Allocation Add");

        fundallocationaddPANEL.setBorder(javax.swing.BorderFactory.createTitledBorder("Add"));

        salariesLABEL.setText("Salaries (RM) :");

        othersLABEL.setText("Others (RM) :");

        unitsLABEL.setText("Units (RM) :");

        facilitiesLABEL.setText("Facilities (RM) :");

        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        descriptionsLABEL.setText("Descriptions :");

        descriptionsTA.setColumns(20);
        descriptionsTA.setRows(5);
        jScrollPane2.setViewportView(descriptionsTA);

        totalLABEL.setText("Total (RM) :");

        javax.swing.GroupLayout fundallocationaddPANELLayout = new javax.swing.GroupLayout(fundallocationaddPANEL);
        fundallocationaddPANEL.setLayout(fundallocationaddPANELLayout);
        fundallocationaddPANELLayout.setHorizontalGroup(
            fundallocationaddPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundallocationaddPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fundallocationaddPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(fundallocationaddPANELLayout.createSequentialGroup()
                        .addGroup(fundallocationaddPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(salariesLABEL, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(facilitiesLABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(unitsLABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fundallocationaddPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salariesTF)
                            .addComponent(unitsTF)
                            .addComponent(facilitiesTF)))
                    .addGroup(fundallocationaddPANELLayout.createSequentialGroup()
                        .addGroup(fundallocationaddPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(descriptionsLABEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(othersLABEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(totalLABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fundallocationaddPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalTF)
                            .addComponent(addBTN)
                            .addComponent(jScrollPane2)
                            .addComponent(othersTF))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        fundallocationaddPANELLayout.setVerticalGroup(
            fundallocationaddPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundallocationaddPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fundallocationaddPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salariesLABEL)
                    .addComponent(salariesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundallocationaddPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitsLABEL)
                    .addComponent(unitsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundallocationaddPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facilitiesLABEL)
                    .addComponent(facilitiesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundallocationaddPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(othersLABEL)
                    .addComponent(othersTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundallocationaddPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundallocationaddPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionsLABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBTN))
        );

        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(fundallocationaddPANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fundallocationaddLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(backBTN)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fundallocationaddLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fundallocationaddPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        try{
                File file = new File("src/main/java/assignment/assignment/TxtFile/OperationsandBudgetPlanning.txt");
                FileWriter fw = new FileWriter(file,true);
                BufferedWriter bw = new BufferedWriter(fw);


                String fileName = "src/main/java/assignment/assignment/TxtFile/OperationsandBudgetPlanning.txt";
                String oabpid = generateNewOabpID(fileName);
                LocalDate oabptdate = java.time.LocalDate.now();
                String salaries = salariesTF.getText();
                String units = unitsTF.getText();
                String facilities = facilitiesTF.getText();
                String others = othersTF.getText();
                String total = totalTF.getText();
                String descriptions = descriptionsTA.getText();
                

                String message = "Are you sure you want to add this new Fund Allocation?\n\n"
                        + "Oabp ID : " + oabpid + "\n"
                        + "Allocation Date : " + oabptdate + "\n"
                        + "Salaries : " + salaries + "\n"
                        + "Units : " + units + "\n"
                        + "Facilities : " + facilities + "\n"
                        + "Others : " + others + "\n"
                        + "Total : " + total + "\n"
                        + "Descriptions : " + descriptions;

                int confirmation = JOptionPane.showConfirmDialog((Component) null, message, "Confirm Add Fund Allocation", JOptionPane.YES_NO_OPTION);

                if (confirmation == JOptionPane.YES_OPTION) {
                    try (PrintWriter pw = new PrintWriter(bw)) {
                        pw.println(oabpid + ";Fund Allocation;" + oabptdate + ";" + salaries + ";" + units + ";" + facilities + ";" + others + ";" + total + ";" + descriptions);
                    }
                    System.out.println("Success");  
                } else {
                    System.out.println("Cancelled by user");
                }

            } catch (IOException e) {
                System.out.println("Fail");
            }
    }//GEN-LAST:event_addBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        OperationsAndBudgetPlanningMenu OperationsAndBudgetPlanningMenu = new OperationsAndBudgetPlanningMenu();
        this.dispose();
        OperationsAndBudgetPlanningMenu.setVisible(true);
    }//GEN-LAST:event_backBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FundAllocationAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FundAllocationAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FundAllocationAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FundAllocationAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FundAllocationAdd().setVisible(true);
            }
        });
    }
    
    public static String generateNewOabpID(String fileName) {
        String lastOabpID = null;
        try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
            String line;
            br.readLine();
            while ((line = br.readLine()) != null) {
                lastOabpID = line;
            }
        } catch (IOException e) {
        }
        
        String NewOabpID;
        if (lastOabpID == null) {
            NewOabpID = "Oabp001";
        } else {
            int num = Integer.parseInt(lastOabpID.substring(4,7));
            num++;
            NewOabpID = "Oabp" + String.format("%03d", num);
        }
        return NewOabpID;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel descriptionsLABEL;
    private javax.swing.JTextArea descriptionsTA;
    private javax.swing.JLabel facilitiesLABEL;
    private javax.swing.JTextField facilitiesTF;
    private javax.swing.JLabel fundallocationaddLABEL;
    private javax.swing.JPanel fundallocationaddPANEL;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel othersLABEL;
    private javax.swing.JTextField othersTF;
    private javax.swing.JLabel salariesLABEL;
    private javax.swing.JTextField salariesTF;
    private javax.swing.JLabel totalLABEL;
    private javax.swing.JTextField totalTF;
    private javax.swing.JLabel unitsLABEL;
    private javax.swing.JTextField unitsTF;
    // End of variables declaration//GEN-END:variables
}
