/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment.assignment.BuildingManagers;

/**
 *
 * @author user
 */
public class OperationsAndBudgetPlanningMenu extends javax.swing.JFrame {

    /**
     * Creates new form managecostmenu
     */
    public OperationsAndBudgetPlanningMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        operationsandbudgetplanningLABEL = new javax.swing.JLabel();
        fundallocationPANEL = new javax.swing.JPanel();
        fundallocationaddBTN = new javax.swing.JButton();
        fundallocationmodifyBTN = new javax.swing.JButton();
        maintenancePANEL = new javax.swing.JPanel();
        maintenanceaddBTN = new javax.swing.JButton();
        maintenancemodifyBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        operationsandbudgetplanningLABEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        operationsandbudgetplanningLABEL.setText("Operations and Budget Planning");

        fundallocationPANEL.setBorder(javax.swing.BorderFactory.createTitledBorder("Manage Fund Allocation"));

        fundallocationaddBTN.setText("Add");
        fundallocationaddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundallocationaddBTNActionPerformed(evt);
            }
        });

        fundallocationmodifyBTN.setText("Modify");
        fundallocationmodifyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundallocationmodifyBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fundallocationPANELLayout = new javax.swing.GroupLayout(fundallocationPANEL);
        fundallocationPANEL.setLayout(fundallocationPANELLayout);
        fundallocationPANELLayout.setHorizontalGroup(
            fundallocationPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundallocationPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fundallocationaddBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(fundallocationmodifyBTN)
                .addContainerGap())
        );
        fundallocationPANELLayout.setVerticalGroup(
            fundallocationPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundallocationPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fundallocationPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fundallocationaddBTN)
                    .addComponent(fundallocationmodifyBTN))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        maintenancePANEL.setBorder(javax.swing.BorderFactory.createTitledBorder("Manage Maintenance"));

        maintenanceaddBTN.setText("Add");
        maintenanceaddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceaddBTNActionPerformed(evt);
            }
        });

        maintenancemodifyBTN.setText("Modify");
        maintenancemodifyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenancemodifyBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout maintenancePANELLayout = new javax.swing.GroupLayout(maintenancePANEL);
        maintenancePANEL.setLayout(maintenancePANELLayout);
        maintenancePANELLayout.setHorizontalGroup(
            maintenancePANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenancePANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maintenanceaddBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(maintenancemodifyBTN)
                .addContainerGap())
        );
        maintenancePANELLayout.setVerticalGroup(
            maintenancePANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenancePANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maintenancePANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maintenanceaddBTN)
                    .addComponent(maintenancemodifyBTN))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fundallocationPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(operationsandbudgetplanningLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backBTN))
                    .addComponent(maintenancePANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(operationsandbudgetplanningLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fundallocationPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maintenancePANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        BuildingManagerMenu BuildingManangerMenu = new BuildingManagerMenu();
        this.dispose();
        BuildingManangerMenu.setVisible(true);
    }//GEN-LAST:event_backBTNActionPerformed

    private void fundallocationaddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundallocationaddBTNActionPerformed
        // TODO add your handling code here:
        FundAllocationAdd FundAllocationAdd = new FundAllocationAdd();
        this.dispose();
        FundAllocationAdd.setVisible(true);
    }//GEN-LAST:event_fundallocationaddBTNActionPerformed

    private void fundallocationmodifyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundallocationmodifyBTNActionPerformed
        // TODO add your handling code here:
        FundAllocationModify FundAllocationModify = new FundAllocationModify();
        this.dispose();
        FundAllocationModify.setVisible(true);
    }//GEN-LAST:event_fundallocationmodifyBTNActionPerformed

    private void maintenanceaddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceaddBTNActionPerformed
        // TODO add your handling code here:
        MaintenanceAdd MaintenanceAdd = new MaintenanceAdd();
        this.dispose();
        MaintenanceAdd.setVisible(true);
    }//GEN-LAST:event_maintenanceaddBTNActionPerformed

    private void maintenancemodifyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenancemodifyBTNActionPerformed
        // TODO add your handling code here:
        MaintenanceModify MaintenanceModify = new MaintenanceModify();
        this.dispose();
        MaintenanceModify.setVisible(true);
    }//GEN-LAST:event_maintenancemodifyBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperationsAndBudgetPlanningMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperationsAndBudgetPlanningMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperationsAndBudgetPlanningMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperationsAndBudgetPlanningMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperationsAndBudgetPlanningMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JPanel fundallocationPANEL;
    private javax.swing.JButton fundallocationaddBTN;
    private javax.swing.JButton fundallocationmodifyBTN;
    private javax.swing.JPanel maintenancePANEL;
    private javax.swing.JButton maintenanceaddBTN;
    private javax.swing.JButton maintenancemodifyBTN;
    private javax.swing.JLabel operationsandbudgetplanningLABEL;
    // End of variables declaration//GEN-END:variables
}
